### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [albertcarrete/ac2292777#2]
Dear albertcarrete,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of NeueHaasGroteskDisp-Bold.otf in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by albertcarrete** [comment]
Fonts have been removed. For future reference, you may not want to link to where you can find and download free fonts in a message regarding potential EULA violations.

**Comment by fontpolice** [comment]
Thank you for your cooperation.
